server:
  port: 9090

spring:
  application:
    name: API_GATEWAY_1
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:Keys/publicKey.pem
  cloud:
    gateway:
      routes:
        - id: chercheur-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/chercheurs/**
        - id: enseignant-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/enseignants/**
        -   id: projet-service
            uri: http://localhost:8050
            predicates:
              - Path=/api/projets/**


